use std::io::Write;
use std::path::Path;

use crate::frequency::WordEntry;

/// Write entries as a JSON array to the given writer.
pub fn write_json<W: Write>(entries: &[WordEntry], mut writer: W) -> Result<(), String> {
    serde_json::to_writer_pretty(&mut writer, entries)
        .map_err(|e| format!("Failed to write JSON: {e}"))
}

/// Write entries as CSV to the given writer.
/// Columns: word, frequency_per_1k, difficulty, sources (JSON-encoded)
pub fn write_csv<W: Write>(entries: &[WordEntry], writer: W) -> Result<(), String> {
    let mut wtr = csv::Writer::from_writer(writer);
    wtr.write_record(["word", "frequency_per_1k", "difficulty", "sources"])
        .map_err(|e| format!("Failed to write CSV header: {e}"))?;

    for entry in entries {
        let sources_json = serde_json::to_string(&entry.sources)
            .map_err(|e| format!("Failed to serialize sources: {e}"))?;
        wtr.write_record([
            &entry.word,
            &format!("{:.6}", entry.frequency_per_1k),
            &entry.difficulty,
            &sources_json,
        ])
        .map_err(|e| format!("Failed to write CSV row: {e}"))?;
    }

    wtr.flush().map_err(|e| format!("Failed to flush CSV: {e}"))
}

/// Write a TypeScript word-list.ts file grouped by difficulty.
///
/// Generates:
///   export const EASY_WORDS: string[] = [...];
///   export const NORMAL_WORDS: string[] = [...];
///   export const HARD_WORDS: string[] = [...];
///   export const WORD_SET = new Set([...EASY_WORDS, ...NORMAL_WORDS, ...HARD_WORDS]);
pub fn write_typescript<W: Write>(entries: &[WordEntry], mut writer: W) -> Result<(), String> {
    let easy: Vec<&str> = entries
        .iter()
        .filter(|e| e.difficulty == "easy")
        .map(|e| e.word.as_str())
        .collect();
    let normal: Vec<&str> = entries
        .iter()
        .filter(|e| e.difficulty == "normal")
        .map(|e| e.word.as_str())
        .collect();
    let hard: Vec<&str> = entries
        .iter()
        .filter(|e| e.difficulty == "hard")
        .map(|e| e.word.as_str())
        .collect();

    writeln!(
        writer,
        "// Auto-generated by tools/word-frequency — do not edit manually."
    )
    .map_err(|e| e.to_string())?;
    writeln!(writer).map_err(|e| e.to_string())?;

    write_ts_array(&mut writer, "EASY_WORDS", &easy)?;
    writeln!(writer).map_err(|e| e.to_string())?;
    write_ts_array(&mut writer, "NORMAL_WORDS", &normal)?;
    writeln!(writer).map_err(|e| e.to_string())?;
    write_ts_array(&mut writer, "HARD_WORDS", &hard)?;
    writeln!(writer).map_err(|e| e.to_string())?;

    writeln!(
        writer,
        "export const WORD_SET = new Set([...EASY_WORDS, ...NORMAL_WORDS, ...HARD_WORDS]);"
    )
    .map_err(|e| e.to_string())?;

    Ok(())
}

fn write_ts_array<W: Write>(
    writer: &mut W,
    name: &str,
    words: &[&str],
) -> Result<(), String> {
    write!(writer, "export const {name}: string[] = [")
        .map_err(|e| e.to_string())?;
    for (i, word) in words.iter().enumerate() {
        if i > 0 {
            write!(writer, ", ").map_err(|e| e.to_string())?;
        }
        write!(writer, "\"{word}\"").map_err(|e| e.to_string())?;
    }
    writeln!(writer, "];").map_err(|e| e.to_string())?;
    Ok(())
}

/// Determine the output path, falling back to stdout indicator ("-") if not set.
/// For TypeScript output targeting the repo, resolve relative to the repo root.
pub fn resolve_output_path(output: Option<&str>, format: &str) -> Option<std::path::PathBuf> {
    if let Some(path) = output {
        Some(Path::new(path).to_path_buf())
    } else {
        match format {
            "typescript" => Some(Path::new("src/game/word-list.ts").to_path_buf()),
            _ => None, // stdout
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::frequency::{SourceEntry, WordEntry};

    fn sample_entries() -> Vec<WordEntry> {
        vec![
            WordEntry {
                word: "apple".to_string(),
                frequency_per_1k: 2.3,
                difficulty: "easy".to_string(),
                sources: vec![SourceEntry {
                    book: "Frankenstein".to_string(),
                    count: 12,
                }],
            },
            WordEntry {
                word: "brave".to_string(),
                frequency_per_1k: 0.5,
                difficulty: "normal".to_string(),
                sources: vec![SourceEntry {
                    book: "Dracula".to_string(),
                    count: 3,
                }],
            },
            WordEntry {
                word: "quirk".to_string(),
                frequency_per_1k: 0.05,
                difficulty: "hard".to_string(),
                sources: vec![],
            },
        ]
    }

    #[test]
    fn test_json_output_contains_fields() {
        let mut buf = Vec::new();
        write_json(&sample_entries(), &mut buf).unwrap();
        let text = String::from_utf8(buf).unwrap();
        assert!(text.contains("\"apple\""));
        assert!(text.contains("\"frequency_per_1k\""));
        assert!(text.contains("\"Frankenstein\""));
    }

    #[test]
    fn test_csv_output_has_header() {
        let mut buf = Vec::new();
        write_csv(&sample_entries(), &mut buf).unwrap();
        let text = String::from_utf8(buf).unwrap();
        assert!(text.starts_with("word,frequency_per_1k,difficulty,sources"));
        assert!(text.contains("apple"));
    }

    #[test]
    fn test_typescript_output_structure() {
        let mut buf = Vec::new();
        write_typescript(&sample_entries(), &mut buf).unwrap();
        let text = String::from_utf8(buf).unwrap();
        assert!(text.contains("export const EASY_WORDS: string[]"));
        assert!(text.contains("export const NORMAL_WORDS: string[]"));
        assert!(text.contains("export const HARD_WORDS: string[]"));
        assert!(text.contains("export const WORD_SET"));
        assert!(text.contains("\"apple\""));
        assert!(text.contains("\"brave\""));
        assert!(text.contains("\"quirk\""));
    }
}
